-- ================================================================================
-- CASE STUDY QUERIES: 01_MARKETING_ROI_ANALYSIS
-- Project Domain: E-Commerce & Retail Business Intelligence
-- Target Platform: Google Cloud BigQuery Standard SQL
-- Data Source Path: `insightengine-sql-analytics.raw_ecommerce.web_events`
-- ================================================================================
-- Business Goal: 
-- Evaluate marketing acquisition channels by volume, unique buyer conversion, 
-- and gross transaction value to optimize ad budget spend across channels.
-- ================================================================================

SELECT 
  traffic_source,
  
  -- Metric 1: Total volume of unique users generated by the channel
  COUNT(DISTINCT user_id) AS total_visitors,
  
  -- Metric 2: Total unique customers who successfully executed a purchase
  COUNT(DISTINCT CASE WHEN event_type = 'purchase' THEN user_id END) AS unique_buyers,
  
  -- Metric 3: Gross dollar value generated directly from purchase events
  ROUND(SUM(CASE WHEN event_type = 'purchase' THEN amount ELSE 0 END), 2) AS total_revenue_usd,
  
  -- Metric 4: Traffic Quality Index (Conversion Rate % of total visitors to buyers)
  ROUND(
    (COUNT(DISTINCT CASE WHEN event_type = 'purchase' THEN user_id END) / COUNT(DISTINCT user_id)) * 100, 
    2
  ) AS conversion_rate_percentage

FROM 
  `insightengine-sql-analytics.raw_ecommerce.web_events`
GROUP BY 
  traffic_source
ORDER BY 
  total_revenue_usd DESC;
